/**
 * Kilo loads JavaScript modules from `.kilo/plugin/` and requires a default descriptor with
 * `{ id, server }`. Declarative hooks.json has no Kilo runtime, so this generator turns its
 * replayable SessionStart commands into that native module. Kilo documents `session.created` as
 * the session lifecycle event; other Claude hook events deliberately remain unsupported until
 * their Kilo payloads have been captured.
 */

interface ClaudeHookItem {
  readonly command?: string;
}

interface ClaudeMatcherGroup {
  readonly hooks?: readonly ClaudeHookItem[];
}

interface ClaudeHooksShape {
  readonly hooks?: Record<string, readonly ClaudeMatcherGroup[]>;
}

interface ParsedHookCall {
  readonly script: string;
  readonly args: readonly string[];
}

const COMMAND_PATTERN = /^node\s+\$\{CLAUDE_PLUGIN_ROOT\}\/hooks\/(\S+)(.*)$/;

function parseCommand(command: string | undefined): ParsedHookCall | null {
  if (typeof command !== "string") return null;
  const match = COMMAND_PATTERN.exec(command.trim());
  if (match === null) return null;
  const [, script, rest] = match;
  return { script, args: rest.trim().length === 0 ? [] : rest.trim().split(/\s+/) };
}

/** Parses only the one declarative event whose Kilo mapping is documented and intended here. */
export function parseKiloSessionStartHooks(rawHooksJson: string): readonly ParsedHookCall[] {
  const parsed = JSON.parse(rawHooksJson) as ClaudeHooksShape;
  return (parsed.hooks?.SessionStart ?? []).flatMap((group) =>
    (group.hooks ?? []).flatMap((hook) => {
      const parsedHook = parseCommand(hook.command);
      return parsedHook === null ? [] : [parsedHook];
    })
  );
}

function toIdentifier(plugin: string): string {
  return `${plugin
    .split("-")
    .filter(Boolean)
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join("")}KiloHooks`;
}

/** Generates Kilo's default plugin descriptor, or no file where hooks.json has no replayable
 * SessionStart command. The generated module keeps errors non-blocking so a failed memory
 * refresh cannot prevent Kilo from creating a session. */
export function generateKiloHooksBridge(rawHooksJson: string, plugin: string): string | null {
  const sessionStart = parseKiloSessionStartHooks(rawHooksJson);
  if (sessionStart.length === 0) return null;
  const identifier = toIdentifier(plugin);
  return `// Generated by aidd from plugins/${plugin}/hooks/hooks.json - do not edit by hand.
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";

const HOOKS_DIR = fileURLToPath(new URL("../hooks/${plugin}/", import.meta.url));
const SESSION_START = ${JSON.stringify(sessionStart)};

function runHook(script, args, payload, directory) {
  const child = spawn("node", [HOOKS_DIR + script, ...args], {
    cwd: directory,
    stdio: ["pipe", "ignore", "ignore"],
    timeout: 5000,
  });
  child.on("error", (error) => reportHookFailure(script, error));
  child.stdin.on("error", (error) => reportHookFailure(script, error));
  child.stdin.end(JSON.stringify(payload));
}

function reportHookFailure(script, error) {
  console.warn("[aidd] Kilo session-start hook " + script + " failed: " + String(error));
}

function sessionStartCallsFor(event, directory) {
  if (event?.type !== "session.created") return [];
  return SESSION_START.map((hook) => ({
    script: hook.script,
    args: hook.args,
    payload: { hook_event_name: "SessionStart", session_id: null, cwd: directory },
  }));
}

const ${identifier} = async ({ directory }) => ({
  event: async ({ event }) => {
    try {
      for (const call of sessionStartCallsFor(event, directory)) {
        runHook(call.script, call.args, call.payload, directory);
      }
    } catch (error) {
      console.warn("[aidd] Kilo session-start hook dispatch failed: " + String(error));
    }
  },
});

${identifier}.sessionStartCallsFor = sessionStartCallsFor;

export default { id: "${plugin}-hooks", server: ${identifier} };
`;
}
